### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by AnthonyFuller** [iViscosity/2FA-Gmod#5]
I will be a beta tester! No worries! I have a test server!

**Comment by AnthonyFuller** [comment]
Also. Mind if I write a wiki for you?

**Comment by iViscosity** [comment]
Hmm, depends on what you mean, as I was in the process of doing so.

**Comment by AnthonyFuller** [comment]
On GitHub or on a website. i.e. MediaWiki Also about the beta testing?

**Comment by AnthonyFuller** [comment]
#4

**Comment by iViscosity** [comment]
Oh yeah feel free to test it if you want. And if you want to make a wiki go ahead, I'll work on it as well.
